Реализовать Блок описания пьеса
DizZer0/lubimovka pull request #11
Opened 2022-06-04 16:27 UTC by MenshikovZakhar

2022-06-05 15:15 UTC, igorpodgorniy requested changes
Всё отлично сделано! Но вот шрифт указан не совсем тот. Подробнее в описании ниже.

2022-06-05 15:15 UTC, igorpodgorniy commented on blocks/description-the-play/__text/description-the-play__text.css
> +    margin: 0 auto 20px auto;
Отступы сделаны корректно) исправлять ничего не нужно здесь.
Но можно короткую запись сделать ещё короче. если есть желание) рекомендую почитать про это на MDN: https://developer.mozilla.org/ru/docs/Web/CSS/margin

2022-06-05 15:15 UTC, igorpodgorniy commented on blocks/description-the-play/__text/description-the-play__text.css
> +    font-family: 'Formular', 'Arial', sans-serif;
Шрифты указаны, как по макету. С этим ок. Но дело в том, что у нас этот шрифт подключен с названием FormularLight. Из-за этого отображается сейчас шрифт Arial, а не желаемый.

2022-06-05 17:40 UTC, igorpodgorniy approved these changes
Тут однозначно лайк)

2022-06-06 19:49 UTC, igorpodgorniy approved these changes
Лайк)

2022-06-07 06:53 UTC, EugeneCod approved these changes

2022-06-07 13:53 UTC, merged