Реализовать блок со слайдером, секция с комментариями
DizZer0/lubimovka pull request #12
Opened 2022-06-04 17:56 UTC by KudenikovNS

Есть моменты не по БЭМу, но я уже закрыл на это глаза.

2022-06-05 18:24 UTC, igorpodgorniy requested changes
Круто, что реализовал слайдер! Всё работает и это не может не радовать)
По мелким правкам расписал ниже в коде, а вот по поводу стрелок в ховере, хотел бы написать здесь.
Обрати внимание, что в ховере стрелки не белые. Предполагаю это связано с тем, что стрелки не в ховере заданы как картинки в src, а стрелки в ховере - как картинка фона. Как вариант, стоит перенести обычные стрелки из src в картинку фона и при наведении менять картинки.

2022-06-05 18:24 UTC, igorpodgorniy commented on blocks/slider-comments/__header/slider-comments__header.css
> +  background-color: #e5e5e5;
К сожалению, цвет фона не соответствует шаблону и стайлгайду. В разделе Цвета и логика указан основной фон: https://www.figma.com/proto/zpyHTGb3aKiAbpJJoIVqQ2/lubimovka?page-id=822%3A11417&node-id=834%3A12347&viewport=11728%2C2764%2C1.1076146364212036&scaling=min-zoom&starting-point-node-id=859%3A13873&hide-ui=1

2022-06-05 18:24 UTC, igorpodgorniy commented on blocks/slider-comments/__title/slider-comments__title.css
> +  margin: 67px 30px 20px 24px;
Верхний отступ по макету 76px. Циферки поменять бы местами)

2022-06-05 18:24 UTC, igorpodgorniy commented on blocks/slider-comments/swiper/swiper-slide/__text/swiper-slide__text.css
> +  font-family: "Formular";
Да, согласно макету шрифт так и называется, но дело в том, что когда шрифты подключали, то этот шрифт обозвали - FormularLight. Из-за этого отображается сейчас другой шрифт.

2022-06-05 18:24 UTC, igorpodgorniy commented on blocks/slider-comments/swiper/swiper-slide/__text/swiper-slide__text.css
> +  line-height: 140%;
Вроде бы договорились множитель писать. Для однообразия я бы всё же поменял на 1.4, но если оставишь так - не беда. Работать будет. Тогда создадим отдельную задачу для того, чтобы всё привести к одному виду написания. Может быть, если время будет.
Если будешь править, то поправь, пожалуйста, во всех местах в своём куске.

2022-06-05 18:24 UTC, igorpodgorniy commented on index.html
> +    <script src="https://unpkg.com/swiper@8/swiper-bundle.min.js"></script>
Ага, вижу подключил готовый слайдер - супер) Будет время и желание - перепишем на свой лад.

2022-06-05 18:24 UTC, igorpodgorniy commented on blocks/slider-comments/swiper/swiper-slide/__text/swiper-slide__text.css
> +  height: 224px;
Так делать не надо. Что произойдёт, если текста в отзыве будет больше? Вот именно. Будет плохо(
Можно же вообще без высота блока текста обойтись.

2022-06-05 18:24 UTC, igorpodgorniy commented on blocks/slider-comments/__title/slider-comments__title.css
> +.slider-comments__title {
Забыл указать у заголовка высоту строки

2022-06-05 18:24 UTC, igorpodgorniy commented on blocks/slider-comments/swiper/swiper-slide/__author/swiper-slide__author.css
> +  margin: 53px 0px 0px 28px;
Не понятно, почему 53px, когда в макете 56. Можно бы было предположить, что если делать по пиксель перфикт и в наложении пришлось убавить отступ, но т.к. шрифт не совпадает, предположу, что не был использован данный плагин. И тогда не понятен выбор такого отступа.

2022-06-05 18:24 UTC, igorpodgorniy commented on index.html
> +          <div class="swiper-wrapper">
По семантике тут напрашивается список.

2022-06-05 18:24 UTC, igorpodgorniy commented on index.html
> +          <div class=".swiper-pagination"></div>
Что-то пошло не так. Класс с точкой.

2022-06-06 13:40 UTC, igorpodgorniy commented on index.html
> +          <div class="swiper-wrapper">
А лучше article

2022-06-08 08:55 UTC, KudenikovNS commented
Сделал исправления, но оставил пока анимацию кнопок как было и слайдер потом переделаю под JS, который Марина написала

2022-06-09 16:40 UTC, igorpodgorniy approved these changes
Насколько я понял, закомментировано для того, чтобы не потерялось.
Потом, конечно, лучше от комментариев избавиться.
После исправления уже не стал выкачивать новую версию, но будем надеяться, что всё ок)

2022-06-13 17:07 UTC, MenshikovZakhar approved these changes

2022-06-13 17:26 UTC, merged