Feat/section4
DizZer0/lubimovka pull request #15
Opened 2022-06-05 19:11 UTC by MarinaKrasnov

2022-06-06 20:43 UTC, Tanya-Osipova commented
Привет! Молодец как много написала и слайдер сделала! 
Но кажется в мобильной версии появляются вертикальные и горизонтальные скроллы и верстка ломается. Или может я что-то не так смотрю? Вот скриншоты.
[](url
![sec4](https://user-images.githubusercontent.com/93708257/172245411-5cab8f33-76af-4cdf-8d2d-2c8e290a7789.jpg)
![sec4 1](https://user-images.githubusercontent.com/93708257/172245492-dbfb5153-afa7-40ab-9752-c7bf1b19e6cd.jpg)
)

2022-06-07 09:49 UTC, MarinaKrasnov commented
> 

на 415px??
у меня нормально.
ты в каком браузере смотришь???

2022-06-07 15:47 UTC, DizZer0 requested changes
Правки только по верстке. в js не осмелился исправлять. У самого пока нет представления, как писать лучше. Кстати, клевая идея с таймером

2022-06-07 15:47 UTC, DizZer0 commented on blocks/slider-btn/slider-btn.css
> +.slider-btn {
Между кнопками должно быть расстояние в 20 px
Предлагаю margin - right 20 px и у last-child отключить его

2022-06-07 15:47 UTC, DizZer0 commented on blocks/slider/__text/slider__text.css
> +  font-family: 'Formular';
Шрифт называется немного по другому "FormularLight"
Не знаю почему название отличается от макета в фигме. Когда шрифты подключал, код был уже готовый

2022-06-07 15:47 UTC, DizZer0 commented on blocks/slider/__dot/slider__dot.css
> +    margin: 16px;
расстояние между точками 16 px, а у тебя получается 16 + 16 = 32px
уменьши вдвое, либо оставь 16 но с одной стороны

2022-06-07 15:47 UTC, DizZer0 commented on index.html
> +             <img class="slider__author" src="./images/more.svg" alt="Читать дальше">
это скорее кнопка, чем картинка. 
так же при наведении курсора, должна быть анимация 
https://www.figma.com/proto/zpyHTGb3aKiAbpJJoIVqQ2/lubimovka?node-id=828%3A12265&starting-point-node-id=859%3A13873

2022-06-10 15:32 UTC, Tanya-Osipova commented
Мне нравится анимация кнопок(previous, next). Очень круто!

2022-06-13 17:06 UTC, MenshikovZakhar approved these changes

2022-06-13 17:45 UTC, Tanya-Osipova approved these changes

2022-06-13 17:45 UTC, Tanya-Osipova commented on blocks/title-h6/title-h6.css
> +}
Можно тут отступы выровнять? Пожааалуйста! :)

2022-06-13 17:45 UTC, Tanya-Osipova commented on blocks/button/button.css
> +}
Можно тут отступы выровнять? Пожааалуйста! :)

2022-06-17 19:06 UTC, DizZer0 approved these changes

2022-06-17 19:32 UTC, merged