Фото и текст
DizZer0/lubimovka pull request #16
Opened 2022-06-06 10:28 UTC by xeniabegunkova

2022-06-06 15:52 UTC, KudenikovNS reviewed
В целом все ок, но есть одно предложение

2022-06-06 15:52 UTC, KudenikovNS commented on blocks/preview-project/__pic/preview-project__pic.css
> +  min-height: 450px;
Max-width and min-height - можно убрать, без них картинка будет сжиматься вместе с контентом, если нужно будет менять размер до 320px

2022-06-06 17:49 UTC, EugeneCod requested changes
Необходимо убрать у текста нижний отступ. Картинка импортирована из мобильной версии макета и в десктопном разрешении визуально не соответствует макету. Поэтому лучше было бы взять картинку из десктопной версии. Ну и если мы все-таки будем подгонять всю верстку до разрешения 320px, то стоит у картинки убрать или установить в значении 320px max-width, да и align-items тоже можно удалить. Предлагаю оставить min-height: 450px, добавить width: 100% и object-fit: cover

2022-06-06 17:49 UTC, EugeneCod commented on blocks/preview-project/__pic-text/preview-project__pic-text.css
> +  padding: 56px 24px 100px 25px;
На данный момент в секции уже установлен нижний padding. Так что этот следует убрать.

2022-06-08 16:44 UTC, EugeneCod approved these changes
Вроде все супер

2022-06-08 16:50 UTC, KudenikovNS approved these changes

2022-06-08 17:14 UTC, merged