Feat/gallery
DizZer0/lubimovka pull request #4
Opened 2022-06-02 16:52 UTC by MenshikovZakhar

2022-06-02 18:04 UTC, igorpodgorniy requested changes
Первый раз провожу ревью. Было сложно.
Структура файлов корректная. Наименование классов по БЭМ. В целом хорошая работа, но к сожалению, на разрешении мобильной версии при ширине 414px фотографии отображаются не два, а в один столбец.
Остальные комментарии оставил в коде.
Спасибо за проделанную работу!)

2022-06-02 18:04 UTC, igorpodgorniy commented on blocks/gallery/__title/gallery__title.css
> +    line-height: 1.1;
Понимаю, что в макете line-height в пикселях и нам приходится высчитывать самим. Предлагаю округлять до двух знаков. То есть 1.14

2022-06-02 18:04 UTC, igorpodgorniy commented on blocks/gallery/__title/gallery__title.css
> +    font-family: 'PPNeueMachina', 'Arial', sans-serif;
Немного поспешил с наименование шрифта. По макету 'Neue Machina'. И тогда будет отображаться, как в макете.

2022-06-02 18:04 UTC, igorpodgorniy commented on blocks/gallery/__items/gallery__items.css
> +    grid-template-columns: repeat(auto-fit, minmax(206px, 1fr));
Ширина мобильной версии 414px. На этом разрешении картинки в одну колонку. Вероятно, стоит поиграть со значениями grid-сетки.

2022-06-02 18:04 UTC, igorpodgorniy commented on blocks/gallery/gallery.css
> +    margin-bottom: 101px;
Хм. Видимо, надо пересмотреть договорённость по отступам внешним и внутренним. Т.к. с внешним отступом в данной ситуации следующий блок будет через белую полосу. Нужен нижних padding. Размер по макету 100px. До кнопки слайдера.

2022-06-02 18:07 UTC, DizZer0 commented on blocks/gallery/__title/gallery__title.css
> +    line-height: 1.1;
и ещё, этот шрифт называется по другому 'Neue Machina'
это на будущее

2022-06-02 18:17 UTC, DizZer0 commented on blocks/gallery/__items/gallery__items.css
> +    grid-template-columns: repeat(auto-fit, minmax(206px, 1fr));
Игорь, ты наверное имел ввиду, что на разрешении 320px картинки будут в одну колонку

2022-06-02 19:31 UTC, DizZer0 approved these changes

2022-06-03 06:03 UTC, igorpodgorniy approved these changes
Отлично!) теперь отображается всё корректно.

2022-06-03 06:03 UTC, merged