сделать часть секции preview-project(section 1). тайтл, время и кнопку купить
DizZer0/lubimovka pull request #6
Opened 2022-06-02 18:56 UTC by DizZer0

2022-06-03 06:54 UTC, igorpodgorniy requested changes
Хорошая работа! Всё соответствует макету, кроме нижнего отступа от кнопки.
В остальном небольшие недочёты по относительной величине высоты строки. Указал это ниже.
Название ветки не соответствует договорённостям. Будь, пожалуйста, внимательнее.
Интересное решение с ховером кнопки. Не сталкивался с таким. 
Когда будешь править у себя в локальной ветки, рекомендую перейти в ветку develop командой git checkout develop
Взять все изменения из удалённой ветки командой git pull. После этого вернуться в свою ветку командой git checkout test
И смерджить у себя локально в ветку test ветку develop командой git merge develop - будет небольшой конaфликт в файле index.css
Должен открыться vscode и там нужно будет разрешить конфликт. Просто оставив строки Захара, ниже поместив свои строки с подключением файлов стилей и убрав всё лишнее

2022-06-03 06:54 UTC, igorpodgorniy commented on blocks/preview-project/__title/preview-project__title.css
> +  line-height: 40px;
Аналогично сабтайтлу. Укажи, пожалуйста, значение в относительно font-size

2022-06-03 06:54 UTC, igorpodgorniy commented on blocks/preview-project/__subtitle/preview-project__subtitle.css
> +  line-height: 24px;
Несмотря на то, что в макете значение высоты строки указано в пикселях, лучше указывать в относительных единицах. Насколько я помню, так будет лучше для версий сайта с разными разрешениями.
Да и в макете для удобства это значение продублировано в процентах: or 120%
Т.е. просто указать 1.2 вместо пикселей.

2022-06-03 06:54 UTC, igorpodgorniy commented on blocks/preview-project/__btn-text/preview-project__btn-text.css
> +  line-height: 22px;
Ниже более подробно описал, для чего необходимо использовать относительные величины при указании высоты строки. Подправь и здесь, пожалуйста.

2022-06-03 06:54 UTC, igorpodgorniy commented on blocks/preview-project/__btn/preview-project__btn.css
> +  margin-bottom: 38px;
Здесь следует указать padding-bottom у всего блока, т.к. расстояние до следующей картинки должно быть закрашено в цвет отличный от белого. В текущей реализации следующий элемент будет от кнопки через белую полосу, что не соответствует макету.

2022-06-03 06:54 UTC, igorpodgorniy commented on blocks/preview-project/__data/preview-project__data.css
> +  line-height: 32px;
И здесь тоже необходимо указать относительную величину

2022-06-03 06:54 UTC, igorpodgorniy commented on blocks/preview-project/__btn/preview-project__btn.css
> +  filter: invert(100%) sepia(5%) saturate(0%) hue-rotate(50deg) brightness(105%) contrast(109%);
что-то на сложном) Данное решение работает, поэтому оставим так. Интересный приём.

2022-06-03 06:54 UTC, igorpodgorniy commented on index.html
> +        <img class="preview-project__btn-union" src="./images/union-right.svg" alt="">
Не указан alt у картинки. Но т.к. это картинка не несущая в себе смысла, то лучше такое делать через background. Но могу ошибаться. Предлагаю для простоты указать alt, и уточнить на будущее, как всё же лучше подобного рода стрелки реализовывать.

2022-06-03 08:35 UTC, KudenikovNS requested changes

2022-06-03 08:35 UTC, KudenikovNS commented on pages/index.css
> +@import url(../blocks/preview-project/preview-project.css);
В самом начале твоих блоков нужно подключить @import url(../blocks/preview-project/preview-project.css), чтобы избежать в дальнейшем того, что свойства родительского блока будут перекрывать свойства элемента частности. В начале подключаем БЛОКИ, потом ЭЛЕМЕНТЫ, потом МОДИФИКАТОРЫ, отсюда и название методологии)) 
@igorpodgorniy по моему ведь так должно быть? Нужен твой совет))

2022-06-03 09:31 UTC, igorpodgorniy commented on pages/index.css
> +@import url(../blocks/preview-project/preview-project.css);
Согласен. Лучше идти от блока к модификаторам. Иначе свойства блока могут перекрыть свойства дочерних элементов. Если у родителя в данном случае только цвет фона задаётся, то в другом случае, может быть что-то ещё задано и тогда это что-то перекроет.

2022-06-03 16:02 UTC, DizZer0 commented on blocks/preview-project/__btn/preview-project__btn.css
> +  filter: invert(100%) sepia(5%) saturate(0%) hue-rotate(50deg) brightness(105%) contrast(109%);
эта строка управляет свойствами svg изображения, вроде как. мне нужна, чтобы менять цвет у стрелки

2022-06-03 16:16 UTC, DizZer0 commented on blocks/preview-project/__btn/preview-project__btn.css
> +  margin-bottom: 38px;
я указал сейчас padding-bottom 100px для preview-project. А тут, в preview-project__btn padding я не могу использовать, иначе бордер у кнопки увеличится

2022-06-03 19:30 UTC, igorpodgorniy approved these changes
Похоже, что всё подправил)
Лайк!)

2022-06-04 06:09 UTC, KudenikovNS approved these changes
Great!

2022-06-04 10:51 UTC, merged