реализовать блок с описанием участников пьесы
DizZer0/lubimovka pull request #7
Opened 2022-06-03 16:00 UTC by EugeneCod

2022-06-03 16:12 UTC, EugeneCod commented
Еще секции 2 присвоен класс: description-the-play

2022-06-04 13:04 UTC, igorpodgorniy requested changes
Хорошая работа! Вёрстка соответствует макету, но на разрешение с шириной 414px появляется горизонтальный скролл. Ниже предложил вариант решения. Но может быть найдёшь что-нибудь интереснее)
Название ветки у тебя интересное) сейчас ничего менять не надо, т.к. работа пока продолжается в этой же ветке. Но на будущее советую как-то покороче называть. Например, feat/working-composition-the-play, ведь над этой частью ты работаешь))
Сейчас при слиянии будет конфликт, т.к. файл index.css используют все. И пока добрались до твоего кода, в удалённом репозитории появились строчки.
Когда будешь править у себя в локальной ветки, рекомендую перейти в ветку develop командой git checkout develop
Взять все изменения из удалённой ветки командой git pull. После этого вернуться в свою ветку командой git checkout <название-твоей-ветки>
И смерджить у себя локально в ветку ветку develop (сорри за тавтологию) командой git merge develop - будет небольшой конaфликт в файле index.css
Должен открыться vscode и там нужно будет разрешить конфликт. Просто оставив строки подключенных ранее стилей, ниже поместив свои строки с подключением файлов стилей и убрав всё лишнее.

2022-06-04 13:04 UTC, igorpodgorniy commented on blocks/working-staff/working-staff.css
> +  width: 414px;
Сейчас блок создаёт вертикальную прокрутку при ширине 414px
Думал. в чём может быть проблема. Сначала на padding правый подумал. Но если его убрать, то блок просто растягивается на этот паддинг. В итоге помогло поставить значение max-width с такой же шириной. Можно попробовать найти другое решение, но в целом, если так будет работать, то и не стоит больше голову ломать)
Заметил момент выше с разделяющей полосой. Поэтому всё же стоит помозговать как лучше сделать.

2022-06-04 13:04 UTC, igorpodgorniy commented on index.html
> +      <section class="working-staff" aria-label="Продолжительность, возрастное ограничение и участники пьесы">
Насколько я понимаю, секция в секции, для того, чтобы вторую часть поместить справа в десктопной версии. Звучит логично. Насколько помню, это не возбраняется, да и сам бы наверное также и сделал бы. Хорошо)

2022-06-04 13:04 UTC, igorpodgorniy commented on index.html
> +      <section class="working-staff" aria-label="Продолжительность, возрастное ограничение и участники пьесы">
Насколько я понимаю, секция в секции, для того, чтобы вторую часть поместить справа в десктопной версии. Звучит логично. Насколько помню, это не возбраняется, да и сам бы наверное также и сделал бы. Хорошо)

2022-06-04 13:04 UTC, igorpodgorniy commented on blocks/working-staff/__age-limit/working-staff__age-limit.css
> +  font-family: 'Neue Machina', Arial, Helvetica, sans-serif;
Хорошо, что указано несколько шрифтов. На тот случай, если кто-то из них не подтянется.
Может быть лучше потом прийти к общему решению. Но сейчас сделано хорошо)

2022-06-04 13:04 UTC, igorpodgorniy commented on blocks/working-staff/__age-limit/working-staff__age-limit.css
> +  font-family: 'Neue Machina', Arial, Helvetica, sans-serif;
Хорошо, что указано несколько шрифтов. На тот случай, если кто-то из них не подтянется.
Может быть лучше потом прийти к общему решению. Но сейчас сделано хорошо)

2022-06-04 13:04 UTC, igorpodgorniy commented on blocks/working-staff/__age-limit/working-staff__age-limit.css
> +  line-height: 1.1428;
Понимаю, что у нас нет стайлгайдов, но вроде бы, в том же Я. Практикуме рекомендуют до двух знаков округлять. Если, конечно, второй знак не ноль.  Я бы сделал для однообразия во всём проекте  округление до двух знаков. Но это как ты решишь.

2022-06-04 13:04 UTC, igorpodgorniy commented on blocks/working-staff/__age-limit/working-staff__age-limit.css
> +  line-height: 1.1428;
Понимаю, что у нас нет стайлгайдов, но вроде бы, в том же Я. Практикуме рекомендуют до двух знаков округлять. Если, конечно, второй знак не ноль.  Я бы сделал для однообразия во всём проекте  округление до двух знаков. Но это как ты решишь.

2022-06-04 13:04 UTC, igorpodgorniy commented on blocks/working-staff/__duration/working-staff__duration.css
> +.working-staff__duration::after {
Решил сделать через after - интересно)
Но я заметил, что если всё же делать max-width для блока, то разделяющая полоса куда-то уезжает. Или перекрывается. Точно сказать не могут. На мой взгляд лучше сделать просто у класса .working-staff__duration значение border-right: 1px solid #242424;
Это как предложение. Не знаю, на каком варианте решения стоит остановится.

2022-06-04 13:04 UTC, igorpodgorniy commented on blocks/working-staff/__duration/working-staff__duration.css
> +.working-staff__duration::after {
Решил сделать через after - интересно)
Но я заметил, что если всё же делать max-width для блока, то разделяющая полоса куда-то уезжает. Или перекрывается. Точно сказать не могут. На мой взгляд лучше сделать просто у класса .working-staff__duration значение border-right: 1px solid #242424;
Это как предложение. Не знаю, на каком варианте решения стоит остановится.

2022-06-05 10:20 UTC, igorpodgorniy approved these changes
Отлично) поправлены все нюансы.

2022-06-05 10:20 UTC, igorpodgorniy commented on blocks/working-staff/working-staff.css
> +  width: 414px;
Сейчас блок создаёт вертикальную прокрутку при ширине 414px
Думал. в чём может быть проблема. Сначала на padding правый подумал. Но если его убрать, то блок просто растягивается на этот паддинг. В итоге помогло поставить значение max-width с такой же шириной. Можно попробовать найти другое решение, но в целом, если так будет работать, то и не стоит больше голову ломать)

2022-06-08 09:02 UTC, KudenikovNS approved these changes
Great!

2022-06-08 11:44 UTC, merged