build: styleguide
DizZer0/lubimovka pull request #8
Opened 2022-06-03 16:53 UTC by MarinaKrasnov

https://www.figma.com/proto/zpyHTGb3aKiAbpJJoIVqQ2/lubimovka?page-id=822%3A11417&node-id=834%3A12347&viewport=11728%2C2764%2C1.1076146364212036&scaling=min-zoom&starting-point-node-id=859%3A13873&hide-ui=1

Использовать в коде следующим образом:
background-color: var(--main-bg-color);

2022-06-04 07:56 UTC, KudenikovNS approved these changes
Видимо это и есть те самые переменные для цвета. 
Я пожалуй ЗА такой подход, ибо ими никогда не пользовался, будет практика))

2022-06-04 11:10 UTC, igorpodgorniy requested changes
Идея с использование css-переменных интересная и полезная. Думаю, нам вместе стоит коллегиально подумать, какие сущности повторяются, чтобы вынести их в переменные и использовать в дальнейшем.
Сейчас это не будет работать, т.к. файл body.css не подключен в главный файл импорта стилей. 
Так же сам класс body сейчас нигде не используется.
И насколько я помню, у класса должен быть свой каталог, т.к. мы договорились работать по БЭМ структуре нестед. Т.е. не в корень blocks расположить файл, а в подкаталог body

2022-06-04 11:10 UTC, igorpodgorniy commented on blocks/body.css
> +.body {
Насколько я вижу, сейчас нигде не используется класс body.

2022-06-04 18:06 UTC, MarinaKrasnov commented on blocks/body.css
> +.body {
нудники , в blocks был класс боди, ну да я не проверила что нигде не прикручен. сейчас слайдером занимаюсь.

2022-06-06 10:34 UTC, Tanya-Osipova commented
А можно в CSS переменные добавить это
```css
--font-family-primary: "FormularLight";
--font-size-md: 16px;
--transition-ln: all 0.3s linear;
--font-style-nm: normal;
--f-weight-nm: 300;
```

2022-06-06 11:12 UTC, MarinaKrasnov commented
> А можно в CSS переменные добавить это
> 
> ```css
> --font-family-primary: "FormularLight";
> --font-size-md: 16px;
> --transition-ln: all 0.3s linear;
> --font-style-nm: normal;
> --f-weight-nm: 300;
> ```

супер идея. 
надо чтобы ребята одобрили и у себя тоже использовали.
по поводу > --font-size-md: 16px; можно просто em использовать, его не нужно объявлять и он 16px по умолчанию. то есть вместо font-size: 16px писать 1em если объявлять  переменную надо будет писать var(--font-size-md)

2022-06-13 17:09 UTC, MenshikovZakhar approved these changes

2022-06-14 17:44 UTC, igorpodgorniy approved these changes

2022-06-14 17:44 UTC, igorpodgorniy commented on blocks/body.css
> +.body {
Насколько я вижу, сейчас нигде не используется класс body.

2022-06-14 17:44 UTC, merged