feat: add header
DizZer0/lubimovka pull request #9
Opened 2022-06-03 19:46 UTC by Tanya-Osipova

2022-06-05 11:16 UTC, igorpodgorniy requested changes
Очень крутая работа! Сделана и мобильная, и десктопная версии! Сделано выезжающее меню на мобильной версии! Супер!)
Может быть из-за этого были упущены кое-какие моменты. Об этом написал комментарии в коде.
Обращаю внимание, что при будущем слиянии будет конфликт, т.к. файл index.css используют все. И пока добрались до твоего кода, в удалённом репозитории появились строчки в этом файле.
Когда будешь править у себя в локальной ветки, рекомендую перейти в ветку develop командой git checkout develop
Взять все изменения из удалённой ветки командой git pull. После этого вернуться в свою ветку командой git checkout <название-твоей-ветки>
И смерджить у себя локально в ветку ветку develop (сорри за тавтологию) командой git merge develop - будет небольшой конaфликт в файле index.css
Должен открыться твой редактор кода и там нужно будет разрешить конфликт. Просто оставив строки подключенных ранее стилей, ниже поместив свои строки с подключением файлов стилей и убрав всё лишнее.

2022-06-05 11:16 UTC, igorpodgorniy commented on blocks/nav/__logo/nav__logo.css
> +  margin-left: 20px;
Сердечко смещено правее, чем на макете. Предлагаю уменьшить значение до 14px, чтобы в сумме с паддингом соответствовало макету на мобильной версии.

2022-06-05 11:16 UTC, igorpodgorniy commented on blocks/aside/__button/aside__button.css
> +  background: #E5E5E5;
Цвет блока определён из макета неверно. Можно, либо выделить в основном макете весь блок perfomance-page и увидеть его цвет: #ECEBE8
Либо посмотреть в стайлгайде к макету (раздел Цвета и логика): https://www.figma.com/proto/zpyHTGb3aKiAbpJJoIVqQ2/lubimovka?page-id=822%3A11417&node-id=834%3A12347&viewport=11728%2C2764%2C1.1076146364212036&scaling=min-zoom&starting-point-node-id=859%3A13873&hide-ui=1

2022-06-05 11:16 UTC, igorpodgorniy commented on blocks/aside/__button/aside__button.css
> +  background: #E5E5E5;
Цвет блока определён из макета неверно. Можно, либо выделить в основном макете весь блок perfomance-page и увидеть его цвет: #ECEBE8
Либо посмотреть в стайлгайде к макету (раздел Цвета и логика): https://www.figma.com/proto/zpyHTGb3aKiAbpJJoIVqQ2/lubimovka?page-id=822%3A11417&node-id=834%3A12347&viewport=11728%2C2764%2C1.1076146364212036&scaling=min-zoom&starting-point-node-id=859%3A13873&hide-ui=1

2022-06-05 11:16 UTC, igorpodgorniy commented on blocks/header/header.css
> +  background: #E5E5E5;
Выше указал, где можно взять корректное значение цвета для блока. Используй, пожалуйста, его

2022-06-05 11:16 UTC, igorpodgorniy commented on blocks/header/header.css
> +  background: #E5E5E5;
Выше указал, где можно взять корректное значение цвета для блока.

2022-06-05 11:16 UTC, igorpodgorniy commented on blocks/header/header.css
> +  padding: 10px;
Сейчас верхний отступ не соответствует макету мобильной версии. Понимаю, что это сделано для того, чтобы хедер выглядел изначально одинаково, когда страница только загружена и когда прокручена.
Можно для только загрузившейся страницы сделать отступ по макету, а у фиксированного хедера поставить как раз верхний отступ равный 10px

2022-06-05 11:16 UTC, igorpodgorniy commented on blocks/header/header.css
> +  padding: 10px;
Сейчас верхний отступ не соответствует макету мобильной версии. Понимаю, что это сделано для того, чтобы хедер выглядел изначально одинаково, когда страница только загружена и когда прокручена.
Можно для только загрузившейся страницы сделать отступ по макету, а у фиксированного хедера поставить как раз верхний отступ равный 10px

2022-06-05 11:16 UTC, igorpodgorniy commented on blocks/aside/__button/aside__button.css
> +  margin: 32px 0 0 30px;
Из-за верхнего margina в 32px на десктопной версии белый фон. Предлагаю обнулить верхний внешний отступ. А у самого блока aside сделать внутренний отступ и задать ему цвет фона.

2022-06-05 11:16 UTC, igorpodgorniy commented on blocks/aside/__button/aside__button.css
> +  margin: 32px 0 0 30px;
Из-за верхнего margina в 32px на десктопной версии белый фон. Предлагаю обнулить верхний внешний отступ. А у самого блока aside сделать внутренний отступ и задать ему цвет фона.

2022-06-05 11:16 UTC, igorpodgorniy commented on blocks/aside/aside.css
> +    display: block;
Вот в этом месте не хватает внутреннего отступа и цвета фона

2022-06-05 11:16 UTC, igorpodgorniy commented on blocks/aside/aside.css
> +    display: block;
Вот в этом месте не хватает внутреннего отступа и цвета фона

2022-06-05 11:16 UTC, igorpodgorniy commented on index.html
> +          <a class="nav__link" href="#">Fb</a>
В макете названия соц.сетей строчными буквами. Вероятно, лучше задать это свойство классу в целом, чтобы каждую надпись не менять.

2022-06-05 11:16 UTC, igorpodgorniy commented on index.html
> +          <a class="nav__link" href="#">Fb</a>
В макете названия соц.сетей строчными буквами. Вероятно, лучше задать это свойство классу в целом, чтобы каждую надпись не менять.

2022-06-05 11:16 UTC, igorpodgorniy commented on index.html
> +  <section  style="width: 50%; height: 100vh; margin: 0 auto; margin-top: 3rem;">
Напоминаю, что этот временный блок можно убрать)

2022-06-05 11:16 UTC, igorpodgorniy commented on index.html
> +  <section  style="width: 50%; height: 100vh; margin: 0 auto; margin-top: 3rem;">
Напоминаю, что этот временный блок можно убрать)

2022-06-05 11:16 UTC, igorpodgorniy commented on scripts/components/nav.js
> +function closeNav() {
Две из трёх функций стрелочные. Не понятно для чего это было сделано. Предлагаю объявлять функции единообразно.

2022-06-05 11:16 UTC, igorpodgorniy commented on scripts/components/nav.js
> +function closeNav() {
Две из трёх функций стрелочные. Не понятно для чего это было сделано. Предлагаю объявлять функции единообразно.

2022-06-05 13:29 UTC, Tanya-Osipova commented on blocks/aside/__button/aside__button.css
> +  margin: 32px 0 0 30px;
Я думала, что вся наша страница будет иметь background: #ECEBE8;
И тогда не будет белого фона.

2022-06-06 15:53 UTC, igorpodgorniy approved these changes
Ну тут однозначно лайк) осталось дождаться ещё одного проверяющего и зальём в главную ветку, если у него не будет доп.вопросов.

2022-06-06 15:53 UTC, igorpodgorniy commented on blocks/nav/__logo/nav__logo.css
> +  margin-left: 20px;
Сердечко смещено правее, чем на макете. Предлагаю уменьшить значение до 14px, чтобы в сумме с паддингом соответствовало макету.

2022-06-06 15:53 UTC, igorpodgorniy commented on blocks/aside/__button/aside__button.css
> +  margin: 32px 0 0 30px;
Ну, можно и так решить данное поведение)

2022-06-07 11:22 UTC, Tanya-Osipova commented
А можно пока не делать merge? Я бы хотела добавить css переменные. Жду когда feat/styleguide merge будет.

2022-06-08 09:20 UTC, KudenikovNS reviewed
Работа офигенная. Думаю чтобы она смотрелась вообще великолепно предлагаю поправить паддинг в header на 30px,

2022-06-08 09:20 UTC, KudenikovNS commented on blocks/header/header.css
> +  padding: 32px 10px 54px;
Сделай первый паддинг 30px и тогда в pixelperfect все будет огонь))

2022-06-08 12:32 UTC, KudenikovNS approved these changes
Все супер)

2022-06-08 12:36 UTC, merged